spring.main.allow-circular-references=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

source.system=GUP
channel= GUP

#logging.level.org.springframework.web=INFO
#logging.level.org.springframework.ws.client.MessageTracing.sent=INFO
#logging.level.org.springframework.ws.server.MessageTracing.sent=INFO
#logging.level.org.springframework.ws.client.MessageTracing.received=INFO

#Collegamento Database BDATA
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USR}
spring.datasource.password=${DATABASE_PWD}
spring.datasource.hikari.connection-timeout=${DATABASE_TIMEOUT}

spring.datasource.hikari.maximum-pool-size=${DATABASE_POOLSIZE:10}
spring.datasource.hikari.max-lifetime= ${DATABASE_MAXLIFE:10000}
spring.datasource.hikari.idle-timeout=${DATABASE_IDLE-TIMEOUT:60000}
spring.datasource.hikari.minimum-idle=${DATABASE_MINIMUM-IDLE:2}
spring.datasource.hikari.pool-name=ConnPoolBlVisualizzaRichDomFisso

#AQ configuration
#aq.oracle.user=${DATABASE_USR}
#aq.oracle.pass=${DATABASE_PWD}
#aq.oracle.url=${DATABASE_URL}
#aq.oracle.min=${MIN_CON}
#aq.oracle.max=${MAX_CON}
#aq.oracle.queue.sblocca=${DATABASE_QUEUE_SBLOCCA}




gup.who.is.nome=bl-visualizza-richiesta-domfisso
gup.who.is.host=${WHO_IS_HOST}
gup.who.is.port=${WHO_IS_PORT}
gup.who.is.path=${WHO_IS_PATH} 
gup.who.is.timeout=${WHO_IS_TIMEOUT}
gup.who.is.protocol=${WHO_IS_PROTOCOL}

