package it.tim.bl.gestione.domfisso.dto;

public class VisualizzaRequestDto {

	private VisualizzazioneRichiestaAttivazioneDomiciliazioneFisso visualizzazioneRichiestaAttivazioneDomiciliazioneFisso;

	public VisualizzazioneRichiestaAttivazioneDomiciliazioneFisso getVisualizzazioneRichiestaAttivazioneDomiciliazioneFisso() {
		return visualizzazioneRichiestaAttivazioneDomiciliazioneFisso;
	}

	public void setVisualizzazioneRichiestaAttivazioneDomiciliazioneFisso(
			VisualizzazioneRichiestaAttivazioneDomiciliazioneFisso visualizzazioneRichiestaAttivazioneDomiciliazioneFisso) {
		this.visualizzazioneRichiestaAttivazioneDomiciliazioneFisso = visualizzazioneRichiestaAttivazioneDomiciliazioneFisso;
	}


	
	
}
